### ISSUE TITLE
bot.py使用nohup报错。。

### ISSUE THREAD

**Issue by WWLoveBasketball** [liuwons/wxBot#202] opened 2017-03-13 09:28 UTC
求问：bot.py，使用nohup后报错：
Traceback (most recent call last):
File "/home/wxBot/wxbot.py", line 774, in proc_msg
self.handle_msg(r)
File "/home/wxBot/wxbot.py", line 747, in handle_msg
self.handle_msg_all(message)
File "bot.py", line 71, in handle_msg_all
self.send_msg_by_uid(self.tuling_auto_reply(msg['user']['id'], msg['content']['data']), msg['user']['id'])
File "bot.py", line 45, in tuling_auto_reply
print ' ROBOT:', result
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-12: ordinal not in range(128)

**Comment by mushroomlb** [comment] 2017-03-13 11:51
"nicodeEncodeError: 'ascii' codec can't encode characters in position 0-12: ordinal not in range(128)",是你字符编码的问题，在文件最上面加上编码 “”# coding: utf-8“”

**Comment by xmcp** [comment] 2017-03-13 11:59
duplicate of #201

**Closed by xmcp** 2017-03-13 11:59 UTC
